apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-entities.yaml
spec:
  type: url
  targets:
    - all-groups.yaml
    - all-components.yaml
    - all-apis.yaml
    - all-domains.yaml
    - all-systems.yaml
