apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: group-1
  description: Group 1
spec:
  type: team
  profile:
    displayName: Group 1
    email: group-1@example.com
    picture: >-
      https://avatars.dicebear.com/api/identicon/group-1.svg?background=%23fff&margin=25
  children: []
